version: '3'

services:
  traefik:
    image: traefik:v2.2
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./cert:/cert:ro
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik.treker.mk`)
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: api-auth
      traefik.http.middlewares.api-auth.basicauth.users: "{{ traefik_auth }}"
    restart: always

networks:
  traefik:
    driver: bridge
